### ISSUE TITLE
User login and permissions

### ISSUE THREAD

**Issue by MichaelSp** [MichaelSp/SocialProjectsHub#1]
- [x] User data model
- [x] Create login form
- [x] Add Login/Logout Buttons
- [x] Create Projects = Everyone, Edit/Delete only authenticated users

**Comment by rpinsler** [comment]
Hi,

I just stumpled upon this project. Good job!
However, maybe I shouldn't be able to go to that page without permission: http://www.socialprohub.org/users
I arrived at that page after I clicked one of the links at the bottom (e.g. contact). After that, the "logout" button as well as a "users" link appeared. When I click it, there is an authorization check sometimes, but not always. Even though another check stopped me from editing any users, I could see all user details (e.g. e-mail addresses).

Best regards,
Robert

**Comment by MichaelSp** [comment]
Thank you for your feedback.
I'm aware of the issue, but unfortunately haven't a solution :disappointed: 
Cause it happens only the deployed version. If I test it locally and in the tests everything works as it should be. So I'm a bit confused...

**Comment by MichaelSp** [comment]
ok, fixed it :D
