### ISSUE TITLE
Owners can't be blank

### ISSUE THREAD

**Issue by kajuside** [MichaelSp/SocialProjectsHub#8]
hi, i can't create my project, the error message i get is: owners can't be blank, but i don't get what it means. merci

![bildschirmfoto 2015-11-21 um 14 06 32](https://cloud.githubusercontent.com/assets/15956140/11318594/63bb377e-9059-11e5-8faa-a95c1fb7e58d.png)

**Comment by kajuside** [comment]
hallo michael,

ich krieg die fehlermeldung aber immer noch…

herzlichst
katharina

Katharina Dermühl

fon: +4915110611924
skype: kajuside

**Comment by MichaelSp** [comment]
Update took a few minutes to deploy. 
Should be working now.
